export const ActionTypes = {
     ADD_PRODUCT : 'ADD_PRODUCT',
     ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
     ADD_PRODUCT_FAIL : 'ADD_PRODUCT_FAIL',
     RESET_ADD_STATUS : 'RESET_ADD_STATUS',
     PRODUCT_UPDATED : 'PRODUCT_UPDATED',
    
     FETCH_PRODUCT : 'FETCH_PRODUCT',
     FETCH_PRODUCT_SUCCESS : 'FETCH_PRODUCT_SUCCESS',
     FETCH_PRODUCT_FAIL : 'FETCH_PRODUCT_FAIL',
    
     FETCH_PRODUCTS : 'FETCH_PRODUCTS',
     FETCH_PRODUCTS_SUCCESS : 'FETCH_PRODUCTS_SUCCESS',
     FETCH_PRODUCTS_FAIL : 'FETCH_PRODUCTS_FAIL',
    
     FETCH_ORDERS : 'FETCH_ORDERS',
     FETCH_ORDERS_SUCCESS : 'FETCH_ORDERS_SUCCESS',
     FETCH_ORDERS_FAIL : 'FETCH_ORDERS_FAIL',
    
     PLACE_ORDER : 'PLACE_ORDER',
     PLACE_ORDER_SUCCESS : 'PLACE_ORDER_SUCCESS',
     PLACE_ORDER_FAIL : 'PLACE_ORDER_FAIL',
    
     ACCEPT_ORDER : 'ACCEPT_ORDER',
     ACCEPT_ORDER_SUCCESS : 'ACCEPT_ORDER_SUCCESS',
     ACCEPT_ORDER_FAIL : 'ACCEPT_ORDER_FAIL',
    
     REJECT_ORDER : 'REJECT_ORDER',
     REJECT_ORDER_SUCCESS : 'REJECT_ORDER_SUCCESS',
     REJECT_ORDER_FAIL : 'REJECT_ORDER_FAIL',
    
     CHANGE_VIEW : 'CHANGE_VIEW',
    

}